Repository magang-mknows/cs, pull requests merged in 2023-03, with the labels that each got.

#4 add system color by figma
  tailwind.config.cjs
Labels: documentation

#9 improvement: remove error
  src/components/molecules/inputs/checkbox-field.tsx
  src/components/molecules/inputs/file-field.tsx
  src/components/molecules/inputs/radio-field.tsx
  src/components/molecules/inputs/select-field.tsx
Labels: bug

#17 Improvement: atoms
  src/components/atoms/button.tsx
  src/components/molecules/card.tsx
  src/components/organisms/sidebar.tsx
  src/components/type.d.ts
  src/layouts/index.tsx
  src/modules/home/index.tsx
  tailwind.config.cjs
Labels: documentation, duplicate, enhancement

#21 feature : add breadcrumb
  src/components/atoms/breadcrumb.tsx
  src/components/atoms/type.d.ts
Labels: enhancement

#22 feature : add auth layout background
  public/assets/auth/asset1.svg
  public/assets/auth/asset2.svg
  public/assets/auth/asset3.svg
  public/assets/auth/logo.svg
  src/layouts/auth/index.tsx
  src/layouts/base/index.tsx
  src/modules/auth/login/index.tsx
  src/modules/home/index.tsx
  src/pages/auth/login.tsx
  src/pages/home/index.tsx
  src/routers/index.tsx
  tailwind.config.cjs
Labels: documentation
