Repository magang-mknows/cs, pull requests merged in 2023-04, with the labels that each got.

#29 improvement: fix login overflow
  src/components/molecules/inputs/text-field/index.tsx
  src/components/molecules/inputs/text-field/types.d.ts
  src/layouts/auth/index.tsx
  src/modules/auth/login/index.tsx
  src/routers/index.tsx
Labels: documentation

#31 improvement: skeleton login
  public/assets/auth/asset1.svg
  public/assets/auth/asset2.svg
  public/assets/auth/asset3.svg
  src/components/organisms/navbar.tsx
  src/layouts/auth/auth-skeleton.tsx
  src/layouts/auth/index.tsx
  src/modules/auth/login/error-login.tsx
  src/modules/auth/login/index.tsx
  src/modules/auth/login/loading-login.tsx
  src/pages/auth/login.tsx
Labels: documentation

#37 improvement : layout on base layout
  index.html
  package.json
  public/logo.png
  src/components/molecules/chart/chart-line.tsx
  src/components/organisms/navbar.tsx
  src/components/organisms/sidebar.tsx
  src/layouts/auth/auth-skeleton.tsx
  src/layouts/auth/index.tsx
  src/layouts/base/index.tsx
  src/modules/home/index.tsx
  src/pages/home/index.tsx
  src/pages/request/index.tsx
  src/routers/index.tsx
  yarn.lock
Labels: documentation

#38 staging production #3
  index.html
  package.json
  public/assets/auth/asset1.svg
  public/assets/auth/asset2.svg
  public/assets/auth/asset3.svg
  public/logo.png
  src/components/molecules/card/index.tsx
  src/components/molecules/chart/chart-line.tsx
  src/components/molecules/inputs/text-field/index.tsx
  src/components/molecules/inputs/text-field/types.d.ts
  src/components/organisms/navbar-sekeleton.tsx
  src/components/organisms/navbar.tsx
  src/components/organisms/sidebar-skeleton.tsx
  src/components/organisms/sidebar.tsx
  src/layouts/auth/auth-skeleton.tsx
  src/layouts/auth/index.tsx
  src/layouts/base/base-skeleton.tsx
  src/layouts/base/index.tsx
  src/modules/auth/login/error-login.tsx
  src/modules/auth/login/index.tsx
  src/modules/auth/login/loading-login.tsx
  src/modules/home/index.tsx
  src/pages/auth/login.tsx
  src/pages/home/index.tsx
  src/pages/request/index.tsx
  src/routers/index.tsx
  yarn.lock
Labels: documentation, duplicate, enhancement

#39 feature : create history page card
  public/assets/dashboard/card1.svg
  public/assets/dashboard/card2.svg
  public/assets/dashboard/card3.svg
  public/assets/dashboard/card4.svg
  src/components/molecules/card/index.tsx
  src/components/type.d.ts
  src/modules/home/card-section.tsx
  src/modules/home/index.tsx
Labels: enhancement

#41 Feature : create base component spinner
  public/loader.png
  src/components/atoms/spinner.tsx
  src/components/molecules/chart/chart-doughnut.tsx
  src/components/organisms/navbar.tsx
  src/components/organisms/sidebar.tsx
  src/layouts/base/index.tsx
  src/modules/home/history-request-section.tsx
  src/modules/home/index.tsx
  src/modules/home/skor-section.tsx
  src/routers/index.tsx
Labels: enhancement

#42 feature : slicing design user page
  src/modules/user/index.tsx
  src/modules/user/table.tsx
  src/pages/user/index.tsx
  src/routers/index.tsx
Labels: enhancement

#43 Bugfixing: layout page user and color text
  src/modules/user/index.tsx
  src/modules/user/table.tsx
Labels: bug

#44 feature: select field
  package.json
  src/components/molecules/inputs/select-field/index.tsx
  src/components/molecules/inputs/select-field/types.d.ts
  yarn.lock
Labels: documentation, enhancement

#45 Feature/report page
  src/modules/report/index.tsx
  src/modules/report/table.tsx
  src/modules/user/index.tsx
  src/pages/report/index.tsx
  src/routers/index.tsx
Labels: enhancement

#46 improvement: report page
  public/assets/pdf.svg
  public/vite.svg
  src/components/molecules/chart/chart-doughnut.tsx
  src/modules/home/history-request-section.tsx
  src/modules/home/index.tsx
  src/modules/report/index.tsx
  src/modules/report/table.tsx
Labels: documentation

#49 add sekeleton on page dashboard,user and report
  src/modules/home/loading-home.tsx
  src/modules/report/loading-report.tsx
  src/modules/user/error-user.tsx
  src/modules/user/loading-user.tsx
  src/pages/home/index.tsx
  src/pages/report/index.tsx
  src/pages/user/index.tsx
  src/routers/index.tsx
Labels: documentation

#73 bugfix : error build
  package.json
  src/components/atoms/icons/ic-delete.tsx
  src/components/atoms/icons/ic-dropdown.tsx
  src/components/atoms/icons/ic-edit.tsx
  src/components/atoms/icons/ic-next.tsx
  src/components/atoms/icons/ic-prev.tsx
  src/components/atoms/icons/ic-search.tsx
  src/components/atoms/icons/ic-table.tsx
  src/components/molecules/chart/chart-bar.tsx
  src/main.tsx
  src/modules/home/age-track.tsx
  src/modules/home/location-tract.tsx
  src/modules/home/salary-track.tsx
  src/modules/report/error.tsx
  src/modules/report/hooks.ts
  src/modules/report/index.tsx
  src/modules/report/loading.tsx
  src/modules/report/store.ts
  src/modules/report/table.tsx
  src/modules/report/type.d.ts
  src/modules/request/error.tsx
  src/modules/request/hasil.tsx
  src/modules/request/hooks.ts
  src/modules/request/loading.tsx
  src/modules/request/proses.tsx
  src/modules/request/request.tsx
  src/modules/request/store.tsx
  src/modules/request/type.d.ts
  src/modules/user/data.tsx
  src/modules/user/error.tsx
  src/modules/user/hooks.ts
  src/modules/user/index.tsx
  src/modules/user/loading.tsx
  src/modules/user/store.ts
  src/modules/user/table.tsx
  src/modules/user/types.d.ts
  src/pages/report/index.tsx
  src/pages/request/index.tsx
  src/pages/user/index.tsx
  src/routers/index.tsx
  yarn.lock
Labels: documentation

#74 Improvement: get data by recoil
  src/components/atoms/icons/ic-warning.tsx
  src/components/molecules/chart/chart-bar.tsx
  src/components/molecules/chart/chart-doughnut.tsx
  src/components/molecules/chart/chart-line.tsx
  src/modules/home/history-request-section.tsx
  src/modules/home/hooks.ts
  src/modules/home/store.ts
  src/modules/home/types.d.ts
  src/modules/report/index.tsx
  src/modules/request/hooks.ts
  src/modules/request/process.tsx
  src/modules/request/request.tsx
  src/modules/request/result.tsx
  src/modules/request/store.ts
  src/modules/request/type.d.ts
  src/modules/request/types.d.ts
  src/modules/user/index.tsx
  src/pages/request/index.tsx
Labels: documentation

#75 Improvement : split component
  src/components/atoms/pagination/index.tsx
  src/components/atoms/search/index.tsx
  src/components/atoms/types.d.ts
  src/components/molecules/card/index.tsx
  src/components/types.d.ts
  src/modules/report/index.tsx
  src/modules/request/process.tsx
  src/modules/request/result.tsx
  src/modules/user/index.tsx
Labels: documentation

#83 feature : add dropdown menu and create modal on table user action delete
  src/components/atoms/dropdownmenu/dashboard.tsx
  src/modules/home/age-track.tsx
  src/modules/home/history-request-section.tsx
  src/modules/home/index.tsx
  src/modules/home/location-tract.tsx
  src/modules/home/request-section.tsx
  src/modules/home/salary-track.tsx
  src/modules/home/skor-section.tsx
  src/modules/user/table.tsx
Labels: documentation

#98 bug fix : klik tab grafik on report page must 2x click for render
  src/components/atoms/search/index.tsx
  src/components/organisms/card-chart/request-section.tsx
  src/components/organisms/sidebar/index.tsx
  src/modules/report/grafik.tsx
  src/modules/report/report.tsx
  src/modules/request/index.css
  src/modules/request/result.tsx
  src/modules/user/index.tsx
  src/modules/user/table.tsx
  src/pages/report/index.tsx
  src/routers/index.tsx
Labels: bug

#106 improvement: new data and design table from figma
  src/modules/home/loading.tsx
  src/modules/report/grafik/index.tsx
  src/modules/report/grafik/loading.tsx
  src/modules/request/result.tsx
  src/modules/request/table.tsx
  src/pages/home/index.tsx
  src/routers/index.tsx
Labels: documentation

#108 improvement: add carousel to card request history
  package.json
  public/assets/dashboard/card5.svg
  public/assets/dashboard/card6.svg
  public/assets/dashboard/card7.svg
  public/assets/dashboard/card8.svg
  public/assets/dashboard/next.svg
  public/assets/dashboard/prev.svg
  src/components/organisms/sidebar/index.tsx
  src/modules/home/error.tsx
  src/modules/home/history-request-section.tsx
  src/modules/home/store.ts
  src/modules/quota/index.tsx
  src/modules/report/report.tsx
  src/modules/report/table.tsx
  src/modules/request/loading.tsx
  src/modules/request/process.tsx
  src/modules/request/store.ts
  src/modules/request/types.d.ts
  src/pages/home/index.tsx
  src/pages/quota/index.tsx
  src/routers/index.tsx
  yarn.lock
Labels: documentation
